- name: configure mysql server
  hosts: mysql
  become: yes # get sudo access/root access
  vars: 
    mysql_sql_root_password: ExpenseApp@1
  tasks:
  - name: Install Mysql Libraries
    ansible.builtin.pip:
     name: "{{ item }}" #pyMySQL
     executable: pip3.9
     Loop:
      - cryptography
      - pyMySQL

  - name: Install Mysql Server
    ansible.builtin.package:
     name: mysql-server
     state: installed

  - name: Start and enable mysql Server
    ansible.builtin.service:
     name: mysqld    
     state: started
     enabled: yes
  
  - name: Connect to mysql Server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_sql_root_password }}" #ExpenseApp@1
      login_host: mysql.devopsdaws82s.online
    register: mysql_info
    ignore_errors: true
  
  - name: Print the output
    ansible.builtin.debug:
      msg: "MySQL Info {{ mysql_info}}"

  - name: Setup root password
    ansible.builtin.command: " mysql_secure-installation --set-root-pass {{ mysql_sql_root_password }} "
    when: mysql_info.failed is true




